const CartActionTypes = {
    TOGGLE_CART_DISPLAY: 'TOGGLE_CART_DISPLAY', 
    TOGGLE_CART_HIDE: 'TOGGLE_CART_HIDE', 
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    DECREASE_ITEM_QUANTITY_FROM_CART: 'DECREASE_ITEM_QUANTITY_FROM_CART'   
}

export default CartActionTypes;